### ISSUE TITLE
add the navbar

### ISSUE THREAD

**Issue by yarelismartin** [nss-evening-cohort-26/gitsub-live-wire#10]
The nav bar should have buttons with event listeners that that direct you to different pages
![image](https://github.com/nss-evening-cohort-26/gitsub-live-wire/assets/153558948/768147a8-1461-4d3c-9d65-dcec2aa63aaf)

# User Story
The user will see a nav bar on every page. 

# Acceptance Criteria
The users will see a bootstrap nav bar with buttons for each tab. 

# Dependecies
No other tickets will impact this ticket as this is part of the HTML structure.

**Comment by Christopher-L-Cole** [comment]
link for bootstrap nav bar
https://getbootstrap.com/docs/4.0/components/navbar/
