### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by yarelismartin** [nss-evening-cohort-26/gitsub-live-wire#12]
the footer will not have functionality unless we have time to add it. 
![image](https://github.com/nss-evening-cohort-26/gitsub-live-wire/assets/153558948/ee169493-050c-42e8-b916-f8d934e6ae0e)

**Comment by Christopher-L-Cole** [comment]
# User Story




When visiting each page/tab the footer will be shown



# Dependecies
- create a div to display the footer items
- no other tickets will be impacted by this ticket's start and finish
