### ISSUE TITLE
create form for project

### ISSUE THREAD

**Issue by yarelismartin** [nss-evening-cohort-26/gitsub-live-wire#16]
![image](https://github.com/nss-evening-cohort-26/gitsub-live-wire/assets/153558948/78e14cca-a025-487b-a0c5-c7c1e189719f)

This form will create a new project that can be pushed to the array of projects

**Comment by Christopher-L-Cole** [comment]
# User Story


# Acceptance Criteria
>When user visits the project page/tab they will see this form to create new projects. 
>Once a name and description is added and the create project button is pressed then it will be added to the projects array above


# Dependecies
> create an array of projects and after we will create a loop to dynamically add the new projects. 

# Dev Notes
> we will need to first create the loop for the new projects to be added into. 
> functionality of the form will not block other tickets
