### ISSUE TITLE
create for loop for project

### ISSUE THREAD

**Issue by yarelismartin** [nss-evening-cohort-26/gitsub-live-wire#24]
![image](https://github.com/nss-evening-cohort-26/gitsub-live-wire/assets/153558948/bd334a20-44b5-489b-9917-cb8333a73a54)

**Comment by Christopher-L-Cole** [comment]
# User Story
User will see the array created of current projects upon visiting the page/ tab. after they use the create project form it will be added to this list of current projects. 

# Acceptance Criteria
- When the user visits the projects page
- THEN they will see a list of current projects
- AND they can add to this array by creating a new project on the form on the page. 


# Dependecies
- need to create an array of projects, then a for loop to render those projects to the DOM

# Dev Notes
- must complete this before the form can function. we need a place to store the added projects
